apiVersion: v1
kind: Service
metadata:
  name: svc-lb-coredns
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.15
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53