apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  volumes:
  - name: app
    emptyDir: {}
  containers:
  - name: web
    image: graywrk/web
    volumeMounts:
    - mountPath: /app
      name: app
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
    livenessProbe:
      tcpSocket: { port: 8000 }
  - name: init
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - mountPath: /app
      name: app

